### ISSUE TITLE
Cleanup Code

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-static#19]
the code has some leftovers that we should cleanup:

- remove `staticBase()` https://github.com/adobe/helix-static/blob/8cac0a0670f9fd8af2d98a2a5db2e13d9f69ba0b/src/index.js#L293-L296
- remove `plain` parameter
- remove `strain` parameter
- decide `path` vs `entry` parameter (I would stick to `path`)

@trieloff  WDYT?

**Comment by RanadeepPolavarapu** [comment]
I'll tackle this.
