### ISSUE TITLE
Use helix-resolve-git-ref

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-static#25]
I assume the "caching" issues visible in https://github.com/adobe/helix-pages/issues/17 are due to the fact that the helix-static action still uses direct git raw api calls (like https://raw.githubusercontent.com/kptdobe/helix-demo/master//style.css) which takes a bit of time to update.
Using https://github.com/adobe/helix-resolve-git-ref like in the pipeline (https://github.com/adobe/helix-pipeline/blob/master/src/utils/resolve-ref.js) should solve that pb.

**Comment by tripodsan** [comment]
similar to pipeline, we should check if the 'ref' is not already a sha. this gives the ability to fetch the sha already in the dispatch, and provide it to all actions.

**Comment by kptdobe** [comment]
So basically, this should happen before, in helix-experimental-dispatch and not here. Same for pipeline. But... the dispatch method tries multiple combinations, like content repo or static repo, htdocs path or root path. This will basically double the number of requests (get first the sha then call the corresponding action) in dispatch.

**Comment by tripodsan** [comment]
...and even worse. it needs to block until the resolve-ref has returned. in the worst case, it has 2 request more: 1 for the static-repo ref, and one for the content-repo ref. most of the times, those are the same.

**Comment by trieloff** [comment]
Closing this one in favor of https://github.com/adobe/helix-experimental-dispatch/issues/3 where it should be addressed.
