### ISSUE TITLE
http2 request to typekit might cause errors

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-static#351]
Requesting `https://theblog-adobe.hlx.page/hlx_fonts/pnv6nym.css` causes a 504.

see https://dashboard.epsagon.com/spans/0e80f2c1-5971-6659-4081-2282a1b3498f

![image](https://user-images.githubusercontent.com/917628/87382834-e42a4180-c5d2-11ea-9e2a-e5183f69cbba.png)

**Comment by tripodsan** [comment]
After a re-deploy of the action the requests work again. Since the fetch-context is kept globally for all activations, one cause could be that it accidentally reused a closed session.

a potential (suboptimal) solution could be to obtain a context for every invocation and destroy the connections afterwards.

**Comment by tripodsan** [comment]
also see https://github.com/adobe/helix-fetch/issues/103

**Comment by stefan-guggisberg** [comment]
fixed in 9b1ecc7
