### ISSUE TITLE
static returns status 400 when requesting a yaml file

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-static#464]
When requesting an existing yaml file (e.g. `test.yaml`) `helix-static` returns status `400`:

```
{
  "code": "jRwI4wBCWfdeO2N9hw5W5PjqvCtoN2FQ",
  "error": "Response type in header did not match generated content type."
}
```

To reproduce:

Add a file `test.yaml` to the root of a repo and then invoke the action:

`curl -v "https://adobeioruntime.net/api/v1/web/helix/helix-services/static@1.13.8?owner=<owner>&repo=<repo>&path=test.yaml"`

or e.g. run this curl command: `curl -v "https://adobeioruntime.net/api/v1/web/helix/helix-services/static@v1?owner=trieloff&repo=helix-demo&path=helix-redirects.yaml"`

cc @trieloff

**Comment by trieloff** [comment]
This looks like an OW-generated error message and typically happens when either the mime type is misdetected or isJSOn/Binary offer the wrong result.

There is a chance that the fix has to happen in helix-deploy, not here.

**Comment by stefan-guggisberg** [comment]
cc @tripodsan WDYT?

**Comment by tripodsan** [comment]
> cc @tripodsan WDYT?

I can look at it next week

**Comment by tripodsan** [comment]
btw, testing with a very old version, produces the same result:

```
curl -sD - 'https://adobeioruntime.net/api/v1/web/helix/helix-services/static@1.10.0?owner=trieloff&repo=helix-demo&ref=528fd4692b6e4cd47ee9a11a133e7c6728b51fe5&path=/helix-redirects.yaml'
HTTP/2 400
content-length: 124
content-type: application/json
x-request-id: IQSSYWsbEFiZZg3aVHhLnOd1MYyAVDlZ
access-control-allow-origin: *
access-control-allow-methods: OPTIONS, GET, DELETE, POST, PUT, HEAD, PATCH
access-control-allow-headers: Authorization, Origin, X-Requested-With, Content-Type, Accept, User-Agent
x-openwhisk-activation-id: c809b1960a12430189b1960a122301e0
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
strict-transport-security: max-age=7884000; includeSubDomains
x-envoy-upstream-service-time: 4505
x-azure-ref: 04rYHYAAAAADR5AUFVIJnTZ7H94FYNKS4VFlPMDFFREdFMDUxOQBiNzdiNjYzMy04ZjcwLTQyNWItOTJiZC03NmFlYmU5YWI5YzU=
date: Wed, 20 Jan 2021 04:51:51 GMT

{
  "code": "IQSSYWsbEFiZZg3aVHhLnOd1MYyAVDlZ",
  "error": "Response type in header did not match generated content type."
}
```

I guess we either never tested this, or this is a regression introduced with the WSK environment change.


note, that if we treat it as binary, and base64 encode the response body, it works.

so waiting for clarification from the runtime team....

**Comment by tripodsan** [comment]
need to add more precise list according to:
https://doc.akka.io/api/akka-http/10.1.11/akka/http/scaladsl/model/MediaTypes$.html

**Comment by tripodsan** [comment]
yes. everything not defined there is binary. so this never worked, we just never tested it. :-)

according to the runtime team:

> I jumped into the old env and it behaves the same way.

https://controller-a-rtbeta2-ue1-a.adobe-runtime.com/api/v1/web/mcdan/default/yaml-test

vs.

https://azure-adobeioruntime.net/api/v1/web/mcdan/default/yaml-test

Both return:

```
{
  "code": "943jr4ToKSh6S75hLLJ1U41IRIGu5dQ0",
  "error": "Response type in header did not match generated content type."
}
```
