### ISSUE TITLE
Add blackbox config

### ISSUE THREAD

**Issue by rofe** [adobe/helix-static#6]
Add a blackbox config with env variables, like we have for other Helix services.

**Comment by tripodsan** [comment]
i don’t think we need this. I would rather use circleci env variables

**Comment by rofe** [comment]
Ok, but I guess we want to restrict the ability to (re)deploy this service to Helix team members.

**Comment by tripodsan** [comment]
> Ok, but I guess we want to restrict the ability to (re)deploy this service to Helix team members.

no. it will be handled by semantic-release and deployed automatically.

**Comment by rofe** [comment]
Gotcha!
